### ISSUE TITLE
'Please set height and width for the chart element' on window resize

### ISSUE THREAD

**Issue by daniel-halldorsson** [chinmaymk/angular-charts#223]
charts is throwing this error whenever i resize my window.

`angular.js:12477 Gracefully handling JS exception: "Error: Please set height and width for the chart element
    at validateHeightAndWidth (http://localhost:7002/bower_components/angular-charts.js:138:15)
    at init (http://localhost:7002/bower_components/angular-charts.js:117:14)
    at http://localhost:7002/bower_components/angular-charts.js:873:11
    at http://localhost:7002/bower_components/angular.js:17855:31
    at completeOutstandingRequest (http://localhost:7002/bower_components/angular.js:5507:10)
    at http://localhost:7002/bower_components/angular.js:5784:7", caused by: undefined`

- I have the height and width set for all charts via CSS
- ive tried using `waitForHeightAndWidth: false` it still happens
- it only happens when i resize brower window
- angular v1.4.7 / angular charts v0.2.7 (installed via bower, bower says 0.2.7 but the bower.json says v0.2.7, not sure what is correct)

cheers

**Comment by MaximilianLloyd** [comment]
I am getting the exact same issue, have you found a solution?

**Comment by fireworkstudio** [comment]
@daniel-halldorsson @MaximilianLloyd 
@carolineBda @umair321 @daniel-halldorsson 
I add two scope variables in directive, and now it works. But this is not a final solution, I am still wait for official resolution.

1) Add two scope variables in directive
![image](https://cloud.githubusercontent.com/assets/13145232/19210042/3679b684-8d4a-11e6-8105-4328821ef96d.jpg)
2) Replace the places using element[0]'s width and height to new variables
![image](https://cloud.githubusercontent.com/assets/13145232/19210045/4facc470-8d4a-11e6-933c-95f89a8723c3.jpg)
3) In your view template, add new attributes
![image](https://cloud.githubusercontent.com/assets/13145232/19210059/94dbfe58-8d4a-11e6-8f8f-1b20952ea991.png)
4) In your controller, define the values
![image](https://cloud.githubusercontent.com/assets/13145232/19210060/b8a0d16a-8d4a-11e6-9467-511b59c82364.png)


You may refer to codes of my project:
[angular-charts.min.js](https://github.com/fireworkstudio/firework-admin/blob/master/firework-admin-web/src/main/webapp/js/lib/angular-charts.min.js)
[dashboard.html](https://github.com/fireworkstudio/firework-admin/blob/master/firework-admin-web/src/main/webapp/views/common/dashboard.html)
[dashboard-controller.js](https://github.com/fireworkstudio/firework-admin/blob/master/firework-admin-web/src/main/webapp/js/controllers/common/dashboard-controller.js)

Here is the screenshot, hope this method will help you solve the problem
![image](https://camo.githubusercontent.com/ecfc8f532f6c488232d2dc947f151d431ff7fa5a/687474703a2f2f37786b6e72382e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f61737365742f7265736f757263652f32303136313030383030323233312e6a70673f696d61676556696577322f322f772f383030)
